## Emporium Sales 

In this project, I’m analyzing sales data for EmporiUm, a growing student bookstore chain that also sells tech gear, art supplies, and other products both in-store and online. The goal of this analysis is to compare sales performance across two territories and better understand what’s driving differences in sales.

------------------------------------------------
#### South Region Territories: Florida and Texas

In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [39]:
customers = pd.read_csv(
    'EmporiUm_files/customer_list.csv',
    sep='|'
)

In [40]:
customers.info() # This displays columns, data types, missing data and number of rows.

<class 'pandas.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cust_id       521 non-null    int64
 1   date          521 non-null    str
 2   time          521 non-null    str
 3   name          521 non-null    str
 4   email         521 non-null    str
 5   phone         520 non-null    str
 6   sms-opt-out   520 non-null    str
dtypes: int64(1), str(6)
memory usage: 28.6 KB

In [41]:
customers.head() # Allows you to preview the first 5 rows

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R. Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N

In [42]:
products = pd.read_csv(
    'EmporiUm_files/products.csv',
    sep='|'
)

products.info()

In [65]:
products.head()

           Prod Num,Product,CategoryID,SubcategoryID
0             105248-IT,TCL NXTPAPER 10s,120,120-tab
1  105249-IT,Dell Latitude 7320 Detachable,120,12...
2                   105250-IT,Realme Pad,120,120-tab
3           105251-IT,Lenovo Tab P12 Pro,120,120-tab
4      105252-IT,Microsoft Surface Pro 9,120,120-tab

In [44]:
ProductCategories = pd.read_csv(
    'EmporiUm_files/ProductCategories.csv',
    sep='|'
)

In [64]:
ProductCategories.info()

<class 'pandas.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cust_id       521 non-null    int64
 1   date          521 non-null    str
 2   time          521 non-null    str
 3   name          521 non-null    str
 4   email         521 non-null    str
 5   phone         520 non-null    str
 6   sms-opt-out   520 non-null    str
dtypes: int64(1), str(6)
memory usage: 28.6 KB

In [46]:
ProductCategories.head()

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R. Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N

In [70]:
StoreDetail = pd.read_csv(
    'EmporiUm_files/StoreDetail.csv',
)

In [71]:
StoreDetail.info()

<class 'pandas.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    str
 1   State              111 non-null    str
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    str
 4   Region             111 non-null    str
 5   Region Director    111 non-null    str
dtypes: int64(1), str(5)
memory usage: 5.3 KB

In [72]:
StoreDetail.head()

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

In [62]:
StoreSales = pd.read_csv(
    'EmporiUm_files/StoreSales.csv',
)

In [66]:
StoreSales.info()

<class 'pandas.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0                335129 non-null  str
 1   Store ID     335129 non-null  int64
 2   RewardsID    34943 non-null   float64
 3   Prod Num     335129 non-null  str
 4   Sale Amount  335129 non-null  float64
dtypes: float64(2), int64(1), str(2)
memory usage: 12.8 MB

In [68]:
StoreSales.head()

             Store ID  RewardsID  Prod Num  Sale Amount
0  1/1/2022       702        NaN  105349-M         8.00
1  1/1/2022       704        NaN  105350-T       144.00
2  1/1/2022       705        NaN  105351-M        44.00
3  1/1/2022       705        NaN  105352-M        47.61
4  1/1/2022       705        NaN  105353-A        20.36

## Core Marketing Analysis

#### 1) Who are the territory managers for the sales territories assigned? What are the store IDs and cities for the stores in each assigned sales territory?

**Lana Ilana** manages the Florida territory.
**Jeff "Howdy" Richards** manages the Texas territory.
The table below displays the store IDs and locations for both territories.

In [78]:
# Filters dataset to include only Florida and Texas stores. 
south_stores = StoreDetail[StoreDetail['State'].isin(['Florida', 'Texas'])]

# Selects only the relevant columns needed for this analysis. 
territory_summary = south_stores[
    ['Territory Manager', 'Store ID', 'Store Location']
    ]

territory_summary # Displays territory manager, store ID, and store location summary.

         Territory Manager  Store ID   Store Location
26              Lana Ilana       719   Cape Canaveral
27              Lana Ilana       720  Fort Lauderdale
28              Lana Ilana       721     Jacksonville
29              Lana Ilana       722         Key West
30              Lana Ilana       723         Lakeland
31              Lana Ilana       724            Miami
32              Lana Ilana       725           Naples
33              Lana Ilana       726          Orlando
34              Lana Ilana       727          Sebring
35              Lana Ilana       728      Tallahassee
36              Lana Ilana       729            Tampa
100  Jeff "Howdy" Richards       901        Arlington
101  Jeff "Howdy" Richards       902           Austin
102  Jeff "Howdy" Richards       903          Bacliff
103  Jeff "Howdy" Richards       904          Baytown
104  Jeff "Howdy" Richards       905         Beaumont
105  Jeff "Howdy" Richards       906       Cedar Park
106  Jeff "Howdy" Richards       907           Dallas
107  Jeff "Howdy" Richards       908           Denton
108  Jeff "Howdy" Richards       909           Desoto
109  Jeff "Howdy" Richards       910       Fort Worth
110  Jeff "Howdy" Richards       911       Georgetown

#### 2) What is monthly total revenue for in-store sales in each of the two sales territories, over the full period covered by the data?